### ISSUE TITLE
All-in-One

### ISSUE THREAD

**Issue by drogga** [yakovlevegor/DroidRec#30] opened 2022-11-30 17:41 UTC
A continuation of the #16 mess.
Now I will have to jump back and forth between the 2...

**Comment by yakovlevegor** [comment] 2022-11-30 17:44
Okay, on the account of the notification error. To be clear, it is unfixable without making use of "androidx" a.k.a "Android Jetpack" garbage framework that Google is forcing on Android developers by deprecating old working apis like Android Support.

**Comment by drogga** [comment] 2022-11-30 17:44
Should've "PolicyLax" cahnge something for me ?, because it didn't...

**Comment by yakovlevegor** [comment] 2022-11-30 18:05
However, I'll try to include AndroidX in app's building process to fix the issue.

**Comment by drogga** [comment] 2022-11-30 18:11
I hate AndroidX too and the Material theming BS.

**Comment by yakovlevegor** [comment] 2022-11-30 19:06
But there's another condition to test. I forgot about the intent flag solution, which AndroidX even suggests in their sources comments, to add `FLAG_GRANT_READ_URI_PERMISSION` and `FLAG_GRANT_WRITE_URI_PERMISSION` to an Intent.
[app-build-permissiongrant.zip](https://github.com/yakovlevegor/DroidRec/files/10126462/app-build-permissiongrant.zip)

**Comment by yakovlevegor** [comment] 2022-11-30 19:14
Wait, it also has an option for `ClipData`. Here's a new one.
[app-build-permissiongrant-clipdata.zip](https://github.com/yakovlevegor/DroidRec/files/10126519/app-build-permissiongrant-clipdata.zip)

**Comment by drogga** [comment] 2022-11-30 20:03
So to test both?

**Comment by yakovlevegor** [comment] 2022-11-30 20:05
Just the latest would suffice.

**Comment by drogga** [comment] 2022-11-30 20:18
Tried with both anyway, multiple times, same outcome.

Maybe build a debug build (those are release builds right?), with LeakCanary, crashlytics, firebase or whatever that might help you...?

**Comment by yakovlevegor** [comment] 2022-11-30 20:19
Nah, this means that I should implement usage of AndroidX somehow. I build the project without Android Studio, only with Android SDK command-line tools, so it would be problematic, because I can't tell Java compiler that I use AndroidX.

**Comment by drogga** [comment] 2022-11-30 20:21
IDK what else I can do to help you, maybe a Log Injection with the help of MT Manager..., I doubt it will help tho.

**Comment by yakovlevegor** [comment] 2022-11-30 20:24
No, the issue is crystal clear. No further logs are needed, thanks.

**Comment by yakovlevegor** [comment] 2022-11-30 21:28
Hmm, or not so fast... I've maybe got a solution. The `FLAG_GRANT_READ_URI_PERMISSION` and `FLAG_GRANT_WRITE_URI_PERMISSION` should be applied to `content://` Uri, not to `file://`.
[app-build-localuri.zip](https://github.com/yakovlevegor/DroidRec/files/10127441/app-build-localuri.zip)

**Comment by yakovlevegor** [comment] 2022-11-30 21:36
I just tested it on an emulator, it works. No `file://` scheme means no Uri exposure. Which means it should be fixed.

**Comment by yakovlevegor** [comment] 2022-12-01 05:39
If Samsung player can't play .m4a, try another player. This is the only format I can provide.

**Comment by drogga** [comment] 2022-12-01 09:41
It's fixed now for the audio, but now the video one ia broken, says `File not found`, the file is obviously there, so maybe you missed something...

**Comment by drogga** [comment] 2022-12-01 09:51
Oh, sorry - in a sec ;), because I'm writing from another device, so I have to copy-transfer-paste those here...

**Comment by drogga** [comment] 2022-12-01 09:58
intent://com.android.externalstorage.documents/tree/primary%3ADCIM%2FScreenshots/document/primary%3ADCIM%2FScreenshots%2FScreenRecording_20221201_115233.mp4#Intent;scheme=content;type=video/mp4;launchFlags=0x13000000;end 
————— 
ACTION: android.intent.action.VIEW 
DATA: content://com.android.externalstorage.documents/tree/primary%3ADCIM%2FScreenshots/document/primary%3ADCIM%2FScreenshots%2FScreenRecording_20221201_115233.mp4 
MIME: video/mp4 
URI: intent://com.android.externalstorage.documents/tree/primary%3ADCIM%2FScreenshots/document/primary%3ADCIM%2FScreenshots%2FScreenRecording_20221201_115233.mp4#Intent;scheme=content;type=video/mp4;launchFlags=0x13000000;end 
FLAGS: 
FLAG_RECEIVER_FOREGROUND 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 

————— 
MATCHING ACTIVITIES: 
Video Player (com.samsung.android.video - com.samsung.android.video.player.activity.MoviePlayer) 
MT Manager (bin.mt.plus - bin.mt.plus.OpenFileActivity) 
Photos (com.google.android.apps.photos - com.google.android.apps.photos.pager.HostPhotoPagerActivity) 
Termux (com.termux - com.termux.filepicker.TermuxFileReceiverActivity) 
MediaInfo (net.mediaarea.mediainfo - net.mediaarea.mediainfo.ReportListActivity)

————

ReSending the intent from rhe "Intent Intercept" to the video player shows: `onActivityResult:: 1 (null)`

**Comment by yakovlevegor** [comment] 2022-12-01 10:53
Seems like `createDocument` function is defective, made it create a non-video file, then rename it to ".mp4".
[app-build-doccreatefix.zip](https://github.com/yakovlevegor/DroidRec/files/10131671/app-build-doccreatefix.zip)

**Comment by drogga** [comment] 2022-12-01 14:21
File not found.

**Comment by yakovlevegor** [comment] 2022-12-01 14:45
Does your video player have storage permission? If audio intent works, could you please intercept it too?

**Comment by yakovlevegor** [comment] 2022-12-01 14:48
Does it work with other video players?

**Comment by drogga** [comment] 2022-12-01 15:04
Yes, it has the needed permissions, I don't have other video players on the device, which one to intercept exactly Audio or Video ?, also how could be a player issue, when it worked until before ypu fixed the audio thing, it doesn't make any sense, does it work for you on your real A10 device, because I'm starting to feel like a pre-alpha tester... If it can't be worked out, then, I will just use the official and accept that I won't be able to play the audio recs. from the app's notification and that's it, I didn't even noticed the issue before the other user mentioned it in his issue anyway.

**Comment by drogga** [comment] 2022-12-01 15:08
Here, since I'm tired: https://github.com/k3b/intent-intercept , you can install it and test it yourself, the intent should be the same as on my devices.

**Comment by yakovlevegor** [comment] 2022-12-01 15:12
>I'm thinking of skipping this alpha\beta testing part and hope that you can figure it out by yourself eventually.

Everything works fine for me on stock Android 9 emulation, it's you who reported the issue, I'm just asking for your abnormal device's specific information.

**Comment by yakovlevegor** [comment] 2022-12-01 15:14
Okay, if it worked before, I'll just try to remove `ClipData` component from the intent. Maybe it's what messes up things.

**Comment by drogga** [comment] 2022-12-01 15:40
`No file found.` with the samsung vid. player, but Yes, it works with "Photos" by google for some reason, I even forgot that it can also play videos, since I don't use it at all, so I admit - my mistake there, sorry.
Could you use whatever was it before, when the video played from the notif. when the Open With prompt was called, but just use whatever the method is used ONLY for the Audio, if it's possible that way at all, IDK since I'm not a coder.

IDK which part of this we are looking at, but here:

intent://com.android.externalstorage.documents/tree/primary%3ADCIM%2FScreenshots/document/primary%3ADCIM%2FScreenshots%2FScreenRecording_20221201_172402.mp4#Intent;scheme=content;type=video/mp4;launchFlags=0x13000000;end 
————— 
ACTION: android.intent.action.VIEW 
DATA: content://com.android.externalstorage.documents/tree/primary%3ADCIM%2FScreenshots/document/primary%3ADCIM%2FScreenshots%2FScreenRecording_20221201_172402.mp4 
MIME: video/mp4 
URI: intent://com.android.externalstorage.documents/tree/primary%3ADCIM%2FScreenshots/document/primary%3ADCIM%2FScreenshots%2FScreenRecording_20221201_172402.mp4#Intent;scheme=content;type=video/mp4;launchFlags=0x13000000;end 
FLAGS: 
FLAG_RECEIVER_FOREGROUND 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 

———— 
MATCHING ACTIVITIES: 
Video Player (com.samsung.android.video - com.samsung.android.video.player.activity.MoviePlayer) 
MT Manager (bin.mt.plus - bin.mt.plus.OpenFileActivity) 
Photos (com.google.android.apps.photos - com.google.android.apps.photos.pager.HostPhotoPagerActivity) 
Termux (com.termux - com.termux.filepicker.TermuxFileReceiverActivity) 
MediaInfo (net.mediaarea.mediainfo - net.mediaarea.mediainfo.ReportListActivity)

**Comment by drogga** [comment] 2022-12-01 15:52
The tricky part is that in order to test with what it will play, if at all and intercept the intent, every time I have to make a new record, even if it's for 2sec., so the notification ca show up, it would've been a lot easier, if it was persistent and it doesn't get dismissed when tapping on it.

For example, here's the intent that `ScrenCam` uses and it works, tho IDK how applicable is here, since the notif. from it, leads to the `Videos` tab inside the app, then I tapped on the video and intercepted this:

intent://com.orpheusdroid.screenrecorder.provider/external_files/DCIM/Screenshots/ScreenCam_01122022_174821.mp4#Intent;scheme=content;type=video/mp4;launchFlags=0x3000000;end 
————— 
ACTION: android.intent.action.VIEW 
DATA: content://com.orpheusdroid.screenrecorder.provider/external_files/DCIM/Screenshots/ScreenCam_01122022_174821.mp4 
MIME: video/mp4 
URI: intent://com.orpheusdroid.screenrecorder.provider/external_files/DCIM/Screenshots/ScreenCam_01122022_174821.mp4#Intent;scheme=content;type=video/mp4;launchFlags=0x3000000;end 
FLAGS: 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 

————— 
MATCHING ACTIVITIES: 
Video Player (com.samsung.android.video - com.samsung.android.video.player.activity.MoviePlayer) 
MT Manager (bin.mt.plus - bin.mt.plus.OpenFileActivity) 
Photos (com.google.android.apps.photos - com.google.android.apps.photos.pager.HostPhotoPagerActivity) 
Termux (com.termux - com.termux.filepicker.TermuxFileReceiverActivity) 
MediaInfo (net.mediaarea.mediainfo - net.mediaarea.mediainfo.ReportListActivity)

**Comment by yakovlevegor** [comment] 2022-12-01 16:01
I'll try to detect if intent is successful or not, and determine if a fallback is needed.

**Comment by drogga** [comment] 2022-12-01 16:18
Do you still need the working interception from an audio rec.?

**Comment by yakovlevegor** [comment] 2022-12-01 16:20
No, not that much. I'll just have to catch an exception when starting an intent.

**Comment by yakovlevegor** [comment] 2022-12-01 16:30
Here is the build, works on an emulator.
[app-build-intentfallback.zip](https://github.com/yakovlevegor/DroidRec/files/10134201/app-build-intentfallback.zip)

**Comment by yakovlevegor** [comment] 2022-12-01 16:33
Exception is not getting detected, the app crashes. Diving into this.

**Comment by yakovlevegor** [comment] 2022-12-01 16:33
I get `Recording error` even on successful intents.

**Comment by drogga** [comment] 2022-12-01 16:36
If you mean `Error: Recording failed`, then as I mentioned - I get it too, nothing unseen.

**Comment by yakovlevegor** [comment] 2022-12-01 16:45
Here, fixed. The version works on an emulator, and falls back to `content://` activity instead of crashing.
[app-build-intentfallbacktake2.zip](https://github.com/yakovlevegor/DroidRec/files/10134328/app-build-intentfallbacktake2.zip)

**Comment by drogga** [comment] 2022-12-01 16:48
Nope.

**Comment by yakovlevegor** [comment] 2022-12-01 16:51
Very unusual, that it worked before. I'll try it with VmPolicy.LAX again.

**Comment by drogga** [comment] 2022-12-01 16:51
So you can't use file provider, like how the file managed does ?

**Comment by yakovlevegor** [comment] 2022-12-01 16:53
It would require adding Google junk and hooking the whole project on Android Studio and Gradle. I have to avoid this.

**Comment by drogga** [comment] 2022-12-01 16:53
Aha, right...

**Comment by drogga** [comment] 2022-12-01 16:58
How the ScreenCam does it then, I pasted the intent above, but I just don't understand it, I guess you can't replicate that too...?

**Comment by yakovlevegor** [comment] 2022-12-01 16:58
The laxed VmPolicy, also removed some attributes from intents.
[app-build-intentfallbackvmlaxtake3.zip](https://github.com/yakovlevegor/DroidRec/files/10134441/app-build-intentfallbackvmlaxtake3.zip)

**Comment by yakovlevegor** [comment] 2022-12-01 16:59
ScreenCam uses root rights, and it uses AndroidX and depends on Gradle itself. https://github.com/yakovlevegor/DroidRec/issues/2#issuecomment-1112282214

**Comment by drogga** [comment] 2022-12-01 17:03
Hurray, finally it worked !!!

I've never used it on a rooted system, but I figured about the dependencies.

**Comment by yakovlevegor** [comment] 2022-12-01 17:04
Audio also works? Just double checking here... 🤨

**Comment by drogga** [comment] 2022-12-01 17:05
Fuck, unfortunately no, damn...

**Comment by yakovlevegor** [comment] 2022-12-01 17:06
Nah, fine. Gonna try dig out the cause.

**Comment by yakovlevegor** [comment] 2022-12-01 17:40
Meanwhile reverted the lax.
[app-build-intentfallbacklaxreverttake4.zip](https://github.com/yakovlevegor/DroidRec/files/10134828/app-build-intentfallbacklaxreverttake4.zip)

**Comment by yakovlevegor** [comment] 2022-12-02 05:18
So it's now in reverse again? My best guess for now is two errors are firing at the same time, causing two exceptions at once, starting two activities at a time. It's not certain, but might as well try and record it to a variable, then start the activity after catching it.

**Comment by yakovlevegor** [comment] 2022-12-02 05:26
Here's my fifth attempt to fix it:
[app-build-intentfallbackrecordfailtake5.zip](https://github.com/yakovlevegor/DroidRec/files/10138301/app-build-intentfallbackrecordfailtake5.zip)

**Comment by yakovlevegor** [comment] 2022-12-02 05:55
On the account of the "Recording error", the message shows when the service receives a "Null" intent. I can just delete that line, as it's useless.

**Comment by drogga** [comment] 2022-12-02 07:18
It's the same, Audio=Yes, Video=No.

**Comment by yakovlevegor** [comment] 2022-12-02 07:47
Okay, I've widened the filter to catch any exception, and removed "Recording error" code. If this build doesn't work, I'll just have to set an explicit workaround with separate defaults for audio and video opening.
[app-build-intentfallbackallexceptionstake6.zip](https://github.com/yakovlevegor/DroidRec/files/10139070/app-build-intentfallbackallexceptionstake6.zip)

**Comment by drogga** [comment] 2022-12-02 08:01
No change, Video=NO.

**Comment by yakovlevegor** [comment] 2022-12-02 08:02
Okay then, means the intent doesn't fail. Then I'm making a workaround for video only.

**Comment by yakovlevegor** [comment] 2022-12-02 08:14
Here, but I'm very confused if this would work, because the error should be detected for audio, not for video intent.
[app-build-intentfallbackseparatevideo7.zip](https://github.com/yakovlevegor/DroidRec/files/10139253/app-build-intentfallbackseparatevideo7.zip)

**Comment by yakovlevegor** [comment] 2022-12-02 08:17
Fixed it, the default intent is `file://` for video.
[app-build-intentfallbackseparatevideofixed7.zip](https://github.com/yakovlevegor/DroidRec/files/10139277/app-build-intentfallbackseparatevideofixed7.zip)

**Comment by drogga** [comment] 2022-12-02 08:31
Not only it doesn't still work for video, but it now also crashes for audio.

**Comment by drogga** [comment] 2022-12-02 08:35
7 (take 1) doesn't crash for audio.

**Comment by yakovlevegor** [comment] 2022-12-02 08:54
Looks like I've messed it twice. `file://` intent was showing on error instead of on video.
[app-build-intentfallbackseparate8.zip](https://github.com/yakovlevegor/DroidRec/files/10139539/app-build-intentfallbackseparate8.zip)

**Comment by drogga** [comment] 2022-12-02 09:08
Still crashes, audio plays.

**Comment by yakovlevegor** [comment] 2022-12-02 09:12
Wait, so, the situation is like this:
1. Audio broken
2. I fixed the video, audio broken
3. Then the opposite

**Comment by yakovlevegor** [comment] 2022-12-02 09:15
I have no idea what I'm doing at this point. Going to experiment again with `ClipData` and `VmPolicy`, something isn't right here.

**Comment by drogga** [comment] 2022-12-02 09:20
> Wait, so, the situation is like this:
> 
> Audio broken
> I fixed the audio, video broken
> Then the opposite

Pretty much...
—
Ok.

**Comment by yakovlevegor** [comment] 2022-12-02 09:20
Oh, got that crash on an emulator too. So now I get it, it's VmPolicy.

**Comment by yakovlevegor** [comment] 2022-12-02 09:24
Previous build with `VmPolicy` lax to avoid crash.
[app-build-intentfallbackseparatelax9.zip](https://github.com/yakovlevegor/DroidRec/files/10139771/app-build-intentfallbackseparatelax9.zip)

**Comment by yakovlevegor** [comment] 2022-12-02 09:28
Actually, the fix would be pointless if the application uses `file://` scheme instead of `content://`, with `VmPolicy` laxed(which doesn't work for Android 11+ any longer). I can't make exclusive fixes just for Smasung player or whatnot.

**Comment by drogga** [comment] 2022-12-02 10:16
Video works, audio doesn't.

Then I guess we leave as is (v2.3 release build) and don't use any of the changes you had to make recently ?

**Comment by yakovlevegor** [comment] 2022-12-02 10:24
No, it would be with working audio, because that solution doesn't touch `VmPolicy` in any way, and utilizes `content://` Uris, which is the best.

**Comment by yakovlevegor** [comment] 2022-12-02 10:25
You've been doing tons of testing work and suggesting features, Thank You!

**Comment by yakovlevegor** [comment] 2022-12-02 12:46
Nevermind the old, I got AndroidX working with the compiler. I'm definitely adding `FileProvider` feature.

**Comment by drogga** [comment] 2022-12-02 13:00
> You've been doing tons of testing work and suggesting features, Thank You!

Thank You too, for everything, really.

**Comment by yakovlevegor** [comment] 2022-12-02 14:02
Now this is odd. With `FileProvider` I too get "Could not read" errors both for audio and video.

**Comment by yakovlevegor** [comment] 2022-12-02 14:03
The Uri is `content://` scheme.

**Comment by yakovlevegor** [comment] 2022-12-02 14:10
Maybe I should consider adding storage permission. The directory picker would remain though.

**Comment by yakovlevegor** [comment] 2022-12-02 21:10
Well, I've got another idea. Instead of passing flags with the intent, I've found a solution to find all the apps that can make use of the intent, and allow each access to the uri by `grantUriPermission` function. It's not a `FileProvider` solution, and I doubt it would work though.
[app-build-grantforeach10.zip](https://github.com/yakovlevegor/DroidRec/files/10144345/app-build-grantforeach10.zip)

**Comment by drogga** [comment] 2022-12-02 23:02
Not only it still doesn't play the videos, but now they don't even have a file extension (.mp4), so I wonder - how the heck G Photos was still able to play those... black magic probably..., jokes aside - I think we should give a chance of\on the storage permissions idea, that would be: read, write, manage, all 3 are probably necessary, along with the legacy storage flag (to deal with the scooped storage BS since 11+).

**Comment by yakovlevegor** [comment] 2022-12-03 06:13
Yes, but note that `file://` scheme still won't be used, because it's forbidden by Android since 7.0. I'll try to make file discovery and permission grant explicit, but if it doesn't work with Jetpack, that would be all I can do.

**Comment by yakovlevegor** [comment] 2022-12-03 06:22
Also I have OneUI 3.1, Samsung plays video without any errors there. So this is definitely ROM-specific.

**Comment by yakovlevegor** [comment] 2022-12-03 07:48
Bingo. `FileProvider` works in conjunction with storage permission for me.

**Comment by yakovlevegor** [comment] 2022-12-03 07:54
Here's what I'm testing currently. Don't forget to explicitly set file storage permission in settings.
[app-build-storagewithfileprovider-11.zip](https://github.com/yakovlevegor/DroidRec/files/10145941/app-build-storagewithfileprovider-11.zip)

**Comment by drogga** [comment] 2022-12-03 08:32
Bingo, finally both play, but it created 0 bytes files without extension along with the actual recordings, which are named exactly as the proper ones, just 0 in size and without ext.
I got: `Error: Recording failed`, probably because of ^ the above.
I guess you will be making it to ask for the permission to be allowed\granted, without users having to figure out by themselves that it should be granted manually form the App Info》Permissions ?, without it, it will crash or fail to record I guess...

**Comment by yakovlevegor** [comment] 2022-12-03 08:33
Yes, the permission will be checked, that build was just the freshest I've got. Glad it finally works.

**Comment by drogga** [comment] 2022-12-03 08:40
Under `Storage` in the `App info`》`External Storage` (`Access to 1 folder/file`) 》 "Deny access" button - will that stay ? (it's the only app I have with it)

**Comment by yakovlevegor** [comment] 2022-12-03 08:45
Denying access is an option, though the app will ask for permissions on record if it's denied.

**Comment by drogga** [comment] 2022-12-03 08:48
That's the idea right ?, that's why you added them in that build...

**Comment by yakovlevegor** [comment] 2022-12-03 08:49
Yes.

**Comment by drogga** [comment] 2022-12-03 08:51
In my opinion, this might've been the problem all together up until now, we should've tried this long ago, like at least 21 builds ago.

**Comment by yakovlevegor** [comment] 2022-12-03 08:53
Wouldn't have worked without `FileProvider` anyway though, since `file://` scheme's forbidden. Alright, now I'm ought to include it in the update.

**Comment by drogga** [comment] 2022-12-03 10:08
Before pushing a official release build, the audio's sample rate needs to be fixed, since you've made 44.1 form 48 days and many builds ago and it was like this for ~1 build and since then it's back to 48 kHz and the bit rate is still 256 kbps, which is unnecessary high, especially for `mono` (1 channel), tho you still haven't mentioned if you can make it record in `stereo`, plus now that AndroidX will be used, is opened for new possibilities, which you wrote that are not possible before, when they were suggested (not only by me) ;)

**Comment by yakovlevegor** [comment] 2022-12-03 10:11
>the audio's sample rate needs to be fixed

It's already back to defaults, plus is detected automatically, if your device can record higher rates.

>which you wrote that are not possible before

AndroidX is just for usability. It doesn't provide screen recording capabilities.

**Comment by drogga** [comment] 2022-12-03 10:42
OK, but even if the device supports 320 kbps audio capturing, that doesn't mean that it makes sense to record it in such a high bit rate, especially when it only in mono, in my opinion it should be pre-set or forced to 128 kbps by default code wise, more than that is excessive and a waste, the same for the sample rate being 48 kHz, it would be amazing if it can also detect that my devices can and is also capable of capturing\recording audio with\in multiple channels and sources, like from the 2 microphones on it, which I get that the 1st party sys apps can take advantage  and use sys APIs with elevated privileges, but 3rd party user installed "audio recorder" apps are also able to record in stereo, without any special low-level privileges, like root or fancy workarounds, this is true since many years, and not only the recent ones, where AndroidX is in existence\a thing, at least I remember recording in stereo on A.5.0 with apps from the Play Store and analyzing the channels with a waveform editor to see and hear is it's not just a placebo - it wasn't, but I don't remember which those apps were, nor I have them anymore, the most recent example, is the PS version of ScreenCam, which can record the audio in stereo (I haven't analysed it) and it also has a option to pick mono or stereo and a option for bitrate, which is not the perfect example, since it's not a voice recorder, but it's what I can at least point to currently as an example, since it's the only example I've seen recently  without digging much, since I don't actually need a voice recorder. Tho those still might not be possible here, because the dependencies\libraries and whatnot junk isn't fully integrated.

Anyway, it's just a suggestion with an example, don't feel a pressure to work on it if it's not worth it or possible ;)

**Comment by yakovlevegor** [comment] 2022-12-03 10:49
I don't have advanced microphone settings. I have "AudioSource.MIC". That's all I have.

**Comment by yakovlevegor** [comment] 2022-12-03 10:58
I can set a number of audio channels for recording, but querying detailed device specs isn't a thing.

**Comment by drogga** [comment] 2022-12-03 10:59
I think `R_Submix` records form the mic. in stereo and internal audio at the same time on <10 without special permissions or root, because playing a music while recording sounds with a good quality and not only captured from the mic., but I have no way of disabling only the mics. with it, so I can't confirm it 100%.

**Comment by yakovlevegor** [comment] 2022-12-03 11:02
>R_Submix records form the mic. in stereo and internal audio

No, remote submix doesn't record internal audio. Only `AudioRecord` can record internal audio, and only since Android 10.

**Comment by drogga** [comment] 2022-12-03 11:12
Oops, my bad, this one can only be used with elevated permissions (at least on A.9), I guess Shizuku can help, but it's not something that regular users would use - NVM > Ignore.

**Comment by drogga** [comment] 2022-12-03 11:40
Maybe in future you can get some examples for the audio options from this project: https://github.com/yrom/ScreenRecorder

**Comment by yakovlevegor** [comment] 2022-12-03 11:40
I can add support up to 8 channels and sample rate settings.

**Comment by yakovlevegor** [comment] 2022-12-03 11:41
I've seen this project already. I think you should read #2.

**Comment by yakovlevegor** [comment] 2022-12-03 11:45
No, 8 channels is for output. I can't add up to 8 input channels. Only as many as supported.

**Comment by yakovlevegor** [comment] 2022-12-03 11:46
Which is two.

**Comment by drogga** [comment] 2022-12-03 11:55
Lol 8 ch's. - not necessarily, 2 would be "stereo" and enough. Thanks in advance.

Yes, I've mentioned it once already, it's because it's so simple and everything is presented right on the main menu \ screen and I like all the options it has, which is everything that I will ever need, too bad that it's abandoned, there's even a PR with fixes there, that there's no one that can or want to merge, so I can't build it with it included, or at least I don't know how, so I can test it, the already build APK is too old and most of the A/V codecs (encoders) are not supported anymore, only 1 of each.

Regarding Issue ticket 2 that you linked: It's for another project (ScreenCam), I've read it, but I don't understand the things you wrote there - sorry.

**Comment by yakovlevegor** [comment] 2022-12-03 13:01
I've read their code too. My point was some recorders utilize Root privileges to access certain system-level permissions, that's all. I can add audio config for channels and custom sample rate, no problem.

**Comment by yakovlevegor** [comment] 2022-12-05 13:05
Looks like Google messed up Android 10 storage compatibility. Because even with `requestLegacyExternalStorage` flag I get `Permission denied` error, meanwhile from Android 11 everything's fine. Going to have to implement sharing without `FileProvider` exclusively for Android 10.

**Comment by yakovlevegor** [comment] 2022-12-05 13:21
Wait, no, my fault. I've set SDCard as a target directory in emulator. Everything works fine with internal storage.

**Comment by yakovlevegor** [comment] 2022-12-05 17:20
No, turns out it's deeper than that. Android 11+ forbids selecting a folder not in "Documents"/" Downloads". Looks like I'll need to implement scoped storage.

**Comment by yakovlevegor** [comment] 2022-12-05 17:50
As there aren't any sharing issues for Android 10+, FileProvider won't be used there.

**Comment by drogga** [comment] 2022-12-07 21:02
The intents for video and audio gets confused a lot, I get the opposite of each many times, but only very rarely the correct ones.

The "Floating controls position" screen is White color, even with the dark theme...

**Comment by drogga** [comment] 2022-12-07 21:59
In my opinion, you should rename the `Use dark theme` option to just `Theme`, the description of which `Set dark theme preferences` to simply write `Dark, Light, Automatic`, or something else, also I think that the `Light` one should be called `White` instead, which of course should also reflect on the entry description of the 3 that I juat suggested.

`Floating controls size` > `Little` and "Small" basically mean the same thing, "Little", I think that the "Little" word isn't really suitable\applicable for describing this option, `Tiny` (which is like I described it when I suggested it) way better name for that one, or even `Smaller` if you like that one more, but not `Little`.

**Comment by drogga** [comment] 2022-12-07 22:03
In my opinion, you should rename the `Use dark theme` option to just `Theme`, the description of which `Set dark theme preferences` to simply write `Dark, Light, Automatic`, or something else, also I think that the `Light` one should be called `White` instead, which of course should also reflect on the entry description of the 3 that I juat suggested.

`Floating controls size` > `Little` and "Small" basically mean the same thing", I think that the "Little" word isn't really suitable\applicable for describing this option, `Tiny` (which is like I described it when I suggested it) way better name for that one, or even `Smaller` if you like that one more, but definitely not `Little`.

**Comment by yakovlevegor** [comment] 2022-12-08 00:21
Here, fixed and renamed settings:
[app-fixedtheme-fixedsettings-latest.zip](https://github.com/yakovlevegor/DroidRec/files/10181093/app-fixedtheme-fixedsettings-latest.zip)

**Comment by yakovlevegor** [comment] 2022-12-08 08:31
Version [2.4](https://github.com/yakovlevegor/DroidRec/releases/tag/v2.4) is out. The fix is in the latest release.

**Comment by drogga** [comment] 2022-12-20 10:34
No app icon on F-Droid (by extension on IzzySoft too)...

**Comment by drogga** [comment] 2023-04-01 10:01
Does the app/`build.gradle` really has to contain the same `android` code that is also in the `AndroidManifest.xml`, or the opposite - the Manifest to contain the same things from that build.gradle file ?, because I think it can be simplified by removing the repeated code from one of the two...

...I might be wrong tho...

**Comment by yakovlevegor** [comment] 2023-04-01 10:07
It's just a precaution measure, for backwards compatibility or whatnot. Though yeah, it's useless.

**Comment by yakovlevegor** [comment] 2023-09-02 06:19
The repository migrates to GitLab, new page for your issue is: https://gitlab.com/egoroyakovlev/DroidRec/-/issues/30

**Closed by yakovlevegor** 2023-09-02 06:19 UTC
Labels: moved gitlab
