### ISSUE TITLE
[Feature Request] Ability to show touches

### ISSUE THREAD

**Issue by Terkyz** [yakovlevegor/DroidRec#21] opened 2022-11-21 18:50 UTC
In many screen recording apps there is a 'Show touches' function, which simply shows a point on the screen in the recording, which simply shows a point in the recording where the user touches the screen, and is quite useful for some occasions. Also, many use the own phone accessibility settings (like xRecorder) to do this, so it may not be that complex to implement.

Thanks for making this app!

**Comment by yakovlevegor** [comment] 2022-11-21 18:59
Showing user's cursor is an option in Android's developer menu. Application can't alter that setting or can't show touches without requesting Root privileges. That feature is only included in Android's default screen recorder app, which is built inside the system. Also, a duplicate of #16.

**Closed by yakovlevegor** 2022-11-21 18:59 UTC
