### ISSUE TITLE
Add features from screencam

### ISSUE THREAD

**Issue by CodeCubeNeo** [yakovlevegor/DroidRec#2] opened 2022-04-28 12:09 UTC
Hello! There is an open source android recording app called screencam, that does support internal audio recording (with the mic), but is unmaintained, and maybe you could use its code for some new features (like internal audio recording, for rooted audio recording and whatnot). It would be great to have a maintained recording app with internal audio (plus screen cam has some anti features...). Here is the link to their source code: https://gitlab.com/vijai/screenrecorder

**Comment by CodeCubeNeo** [comment] 2022-04-28 13:13
So the screencam app uses the same api for recording as you?

**Comment by CodeCubeNeo** [comment] 2022-04-28 14:20
But what is the difference, between their "internal audio" and "mic" recording

**Comment by yakovlevegor** [comment] 2022-04-28 15:56
And I am **not** writing any root extensions to modify the system and support system audio recording. That's Android's fault.

**Comment by WorldWonderful10** [comment] 2022-07-31 23:31
> Okay, I've installed it, and confirm that the app requires root privileges to record system audio. ![Screenshot_20220428-212753_ScreenCam](https://user-images.githubusercontent.com/97333581/165776057-b409cbd8-efcb-44a3-94c7-cf7c94c40608.jpg)
> 
> That means ScreenCam can **not** record system audio by itself, and no other Android app can do it either.

Since android 10 is possible [record audio from](https://medium.com/@juliozynger/media-projection-and-audio-capture-1ca72e271e9c) system with MediaProjection.

**Comment by CodeCubeNeo** [comment] 2022-08-01 06:24
Awesome

**Comment by yakovlevegor** [comment] 2022-10-27 12:19
@WorldWonderful10, I just tested, AudioRecord works very well on Android 10+. The only downside is that `MediaMuxer` class doesn't support changing screen orientation on the go, so each time the orientation changes the recording is gonna have to stop and start again, creating a new file. Your suggestion saved me lots of time. The feature if confirmed for the next version. Thanks a lot!

**Comment by yakovlevegor** [comment] 2022-10-30 18:24
The new version with the implementation is out. I'm closing the issue.

**Closed by yakovlevegor** 2022-10-30 18:24 UTC
