### ISSUE TITLE
[enhancement] option to turn dark mode on

### ISSUE THREAD

**Issue by Vilianexe** [yakovlevegor/DroidRec#17] opened 2022-11-13 21:57 UTC
Hello, i love the simplicit of the app, but can you add an option to turn dark mode?, or change the white backgroud color to black?
Thank you!

**Comment by drogga** [comment] 2022-11-14 11:11
#16 is literally the same...

**Comment by yakovlevegor** [comment] 2022-11-15 19:19
Duplicate of #16

**Closed by yakovlevegor** 2022-11-15 19:19 UTC
