### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Waa11a** [yakovlevegor/DroidRec#13] opened 2022-11-03 00:52 UTC
Device name: vivo V23e 5G
android 12

![Screenshot_20221103_025007](https://user-images.githubusercontent.com/89239945/199628700-bea2954e-b9d8-403d-8bb2-44232cdba3b4.jpg)

**Comment by yakovlevegor** [comment] 2022-11-03 02:15
Version [1.5](https://github.com/yakovlevegor/DroidRec/releases/tag/v1.5) just came out. Also a duplicate of #11

**Closed by yakovlevegor** 2022-11-03 02:15 UTC
